mapa/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('mapa', views.mapa, name='mapa'),
    path('lugarocupado', views.lugarocupado, name='lugarocupado'),
    path('propina', views.propina, name='propina'),
    path('calificar', views.calificar, name='calificar'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('', include('mapa.urls')),
]

mapa/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models


class Registro(models.Model):
    nombre = models.CharField(max_length=20)
    apellido = models.CharField(max_length=20)
    ci = models.IntegerField()
    num_registro = models.IntegerField(primary_key=True)
    direccion = models.TextField(default=None, null=True)
    nombre_trabajo = models.CharField(max_length=50)
    latitud = models.FloatField(default=0)
    longitud = models.FloatField(default=0)
    horario_inicio = models.TimeField(default=None, null=True)
    horario_fin = models.TimeField(default=None, null=True)

    def __str__(self):
        return "num_reg: {}".format(self.num_registro)


class Cuidacoches(models.Model):
    nombre = models.CharField(max_length=20)
    apellido = models.CharField(max_length=20)
    ci = models.IntegerField()
    num_registro = models.IntegerField(primary_key=True)
    direccion = models.TextField(default=None, null=True)
    horario_inicio = models.TimeField(default=None, null=True)
    horario_fin = models.TimeField(default=None, null=True)
    telefono = models.IntegerField(null=True)
    mail = models.EmailField(default=None, null=True)
    fecha_nacimiento = models.DateField(null=True)
    cuenta_bancaria = models.IntegerField(null=True)
    banco = models.CharField(max_length=50, null=True)
    promedio_calificacion = models.FloatField(null=True)
    cantidad_votos = models.IntegerField(null=True)
    estado = models.BooleanField(default=True)
    cant_lugares = models.IntegerField(default=20)
    lugares_disponibles = models.IntegerField(default=cant_lugares)
    password = models.CharField(max_length=8, null=True)
    nombre_trabajo = models.CharField(max_length=50)
    latitud = models.FloatField(default=0)
    longitud = models.FloatField(default=0)



    def __str__(self):
        return "num_reg cuidacoches: {}".format(self.num_registro)


class MonederoCuidacoches(models.Model):
    ci = models.ForeignKey(Cuidacoches, on_delete=models.CASCADE)
    monto = models.IntegerField(null=False)

    def agregar_propina(self, propina):
        self.monto += propina
        self.save()


class Conductor(models.Model):
    nombre = models.CharField(max_length=20)
    apellido = models.CharField(max_length=20)
    ci = models.IntegerField(unique=True, null=True)
    telefono = models.IntegerField(null=True)
    mail = models.EmailField(null=True)
    cuenta_bancaria = models.IntegerField(null=True)
    banco = models.CharField(max_length=50)
    estado = models.BooleanField(default=True)
    username = models.CharField(max_length=20, default="user", null=True)
    password = models.CharField(max_length=8, null=True)
    notificacion = models.IntegerField(null=False, default=0)

    def __str__(self):
        return "ci conductor: {}".format(self.ci)

    def alta_conductor(self):
        self.save()

    def baja_conductor(self):
        self.estado = False
        self.save()

    def editar_conductor(self):
        self.save()


class MonederoConductor(models.Model):
    ci = models.ForeignKey(Conductor, on_delete=models.CASCADE)
    monto = models.IntegerField(default=500)

    def dar_propina(self, propina):
        self.monto -= propina
        self.save()


class Relacion(models.Model):
    id = models.AutoField(primary_key=True, null=False)
    cuidacoches = models.ForeignKey(Cuidacoches, on_delete=models.CASCADE)
    conductor = models.ForeignKey(Conductor, on_delete=models.CASCADE)
    calificacion = models.IntegerField(null=True)
    comentario = models.TextField(max_length=200, null=True)
    fecha = models.DateTimeField(auto_now=True)
    propina = models.IntegerField(null=True)

    def alta_relacion(self):
        self.save()

    def calificar(self, calificacion):
        self.calificacion = calificacion
        self.save()

    def comentar(self, comentario):
        self.comentario = comentario
        self.save()

mapa/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from myapp.models import Cuidacoches


def mapa(request):
    template = loader.get_template('mapa.html')
    coordenadas = Cuidacoches.objects.all()
    return render(request, 'mapa.html', {'coordenadas': coordenadas})


def lugarocupado(request):
    template = loader.get_template('lugarocupado.html')
    nombre_lugar_trabajo = request.POST['nombre_lugar_trabajo']
    nombre = request.POST['nombre']
    apellido = request.POST['apellido']
    horario_inicio = request.POST['horario_inicio']
    horario_fin = request.POST['horario_fin']
    codigo = "Usted estaciono en la calle "+ nombre_lugar_trabajo + " la persona que cuida su vehiculo es "+ nombre +" "+ apellido + ".Su cuidacoches estara disponible desde las " + horario_inicio + " Hasta las "+ horario_fin
    return render(request, 'lugarocupado.html', {'codigo': codigo})


def propina(request):
    template = loader.get_template('propina.html')
    return HttpResponse(template.render({}, request))


def calificar(request):
    template = loader.get_template('calificar.html')
    return HttpResponse(template.render({}, request))

templates/acerca_de.html
{% extends 'base.html' %}
{% load static %}
{% block title %}TLC Inicio{% endblock %}

{% block content %}
<section class="view intro-1 hm-black-strong">
    <div class="full-bg-img flex-center">
        <div class="container">

    

    <div style="background-color: rgba(255, 255, 255, 0.8); color: rgb(0, 19, 104);">
        <div style="margin: 20px;">

            <img src=" {% static 'img/Acerca_de.png' %} " alt="no carga" width="100%">
        </div>


    </div>

    
</div>
</div>
</section>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="full-height">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>{% block title %}{% endblock %}</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    {% block links %} {% endblock %}
    
    <style>
  
        body{
            font-family:'Poppins', 'Times New Roman', serif;
        }

        .flex-center {
            color: #fff;
        }
        .intro-1 {
            background: url("https://aldianews.com/sites/default/files/articles/montevideo_grande.jpg")no-repeat center center;
            background-size: cover;
        }
        .navbar .btn-group .dropdown-menu a:hover {
            color: #000 !important;
        }

        .navbar .btn-group .dropdown-menu a:active {
            color: #fff !important;
        }

        .full-bg-img {
            background-color: rgba(129, 215, 255, 0.5) !important; 
        }

        .jumbotron {
            background-color: rgb(39, 170, 225);
            }

        body {
                margin: 0;
                padding: 0;
            }
        #map {
                position: relative;
                top: 0;
                bottom: 0;
                width: 100%;
                height: 100%;
                margin-top: 150px;
                margin-right: 6px;
                margin-left: 10px;
            }
        .marker {
                background-image: url('mapbox-icon.png');
                background-size: cover;
                width: 50px;
                height: 50px;
                border-radius: 50%;
                cursor: pointer;
            }
        .mapboxgl-popup {
                max-width: 200px;
            }
        .mapboxgl-popup-content {
                text-align: center;
                font-family: 'Open Sans', sans-serif;
            }
        .star-rating {
                direction: rtl;
                display: inline-block;
                padding: 20px
            }

            .star-rating input[type=radio] {
                display: none
            }

            .star-rating label {
                color: rgb(133, 142, 192);
                font-size: 50px;
                padding: 0;
                cursor: pointer;
            /*    -webkit-transition: all .3s ease-in-out;
                transition: all .3s ease-in-out  */
            }

            .star-rating label:hover,
            .star-rating label:hover ~ label,
            .star-rating input[type=radio]:checked ~ label {
                color: #ffbf00
            }



    </style>

</head>

<body>

    <header>

        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark elegant-color-dark fixed-top" style="background-color: #00639c !important;">
            <div class="container">
                <a class="navbar-brand" href="#">TeLoCuido Parking</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'portada' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'quienes_somos' %}">Quienes somos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'como_funciona' %}">Cómo funciona</a>
                        </li>
                        {% if tipo == 'cuidacoches'%}
                        <li class="nav-item btn-group">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cuidacoches 
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'home_cuidacoches' %}">Inicio</a>
                                <a class="dropdown-item" href="{% url 'monedero_cuidacoches' %}">Perfil</a>
                            </div>
                        </li>
                        {% elif tipo == 'conductor'%}
                        <li class="nav-item btn-group">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Usuario 
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'home_conductor' %}">Mapa</a>
                                <a class="dropdown-item" href="{% url 'servicios_conductor' %}">Transacciones</a>
                            </div>
                        </li>
                        {% endif %}
                        <li class="nav-item float-right">
                            {% if tipo == 'cuidacoches'%}
                            <a class="nav-link" href="{% url 'logout' %}">Salir</a>
                            {% endif %}
                            {% if tipo == 'conductor'%}
                            <a class="nav-link" href="{% url 'logout' %}">Salir</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!--/.Navbar-->

        

                        {% block content %}
                        {% endblock %}

        </div>

    </header>

    <!-- Main container-->



    <!--Footer-->
    <footer class="page-footer center-on-small-only elegant-color-dark" style="background-color: #00639c !important;">

        <!--Footer Links-->


        <hr>


        <!--Copyright-->
        <div class="footer-copyright">
            <div class="container-fluid">
                © 2020 <a href=""> Grupo WOOW </a>

            </div>
        </div>
   

    </footer>
    <!--/.Footer-->


    <!-- SCRIPTS -->

    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    
    <!-- Bootstrap dropdown -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

    <!-- Animations init-->
    <script>
        new WOW().init();
    </script>

{% block script %}

{% endblock %}


</body>

</html>

templates/estacionado.html
{% extends 'base.html' %}
{% load static %}
{% block title %}TLC Inicio{% endblock %}

{% block content %}
<section class="view intro-1 hm-black-strong">
    <div class="full-bg-img flex-center">
        <div class="container" >
            <div style="background-color: rgba(255, 255, 255, 0.8); color: rgb(0, 19, 104);">
<div style=" text-align: center;">
    <p style="margin: auto;">
        <ul><li><br></li>
            <li>Usted estacionó en {{rel.cuidacoches.nombre_trabajo}}.</li>
            <li>La persona que cuida su vehículo es {{rel.cuidacoches.nombre}} {{rel.cuidacoches.apellido}}. </li>
            <li>Su cuidacoches estará disponible desde las {{rel.cuidacoches.horario_inicio}} hasta las {{rel.cuidacoches.horario_fin}}.</li>
            <li><br></li>
            <li><a href="{% url 'rel' %}" class="btn btn-primary">Despejar lugar</a></li>
            <li><br></li>
        </ul>
    </p>
</div>

</div>
</div>
</section>

{% endblock %}

templates/home_cuidacoches.html
{% extends 'base.html' %}
{% load static %}
{% block title %}TLC Inicio{% endblock %}

{% block content %}
<section class="view intro-1 hm-black-strong">
    <div class="full-bg-img flex-center">
        <div class="container">

    

    <div style="background-color: rgba(255, 255, 255, 0.8); color: rgb(0, 19, 104);">
<!--------------------------------------------contenido------------------------------------------------------------------------>
<div style="margin: 20px;">

    <ul>
        <li> <br> </li>
        <li><h3>Gestionar lugares</h3></li>
        <li><br></li>    
        <li>
            <h1><strong style="color: green;">{{cuidacoches.lugares_disponibles}}</strong></h1>
            <h4>Lugares disponibles</h4>
            <form method="POST" >
                {% csrf_token %}
                {{ LiberarForm.as_p }}
                <button class="btn btn-success" type="submit">LIBERAR ESPACIO</button>
            </form>
        </li>
        <li> <br><br> </li>
        <li>
            <h1><strong style="color: red;">{{lugOcupados}}</strong></h1>
            <h4>Lugares Ocupados</h4>
            <form method="POST" >
                {% csrf_token %}
                {{ OcuparForm.as_p }}
                <button class="btn btn-danger" type="submit">OCUPAR ESPACIO</button>
            </form>
        </li>
        <li><br></li>
    </ul>

</div>
<!------------------------------------------------------------------------------------------------------------------------------->


    </div>

    
</div>
</div>
</section>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}TLC Inicio{% endblock %}

{% block content %}
<section class="view intro-1 hm-black-strong">
    <div class="full-bg-img flex-center">
        <div class="container">

    

    <div style="background-color: rgba(255, 255, 255, 0.8); color: rgb(0, 19, 104);">
        <h3 style="text-align: center;"> {{mensaje}} </h3>
        <br>
        <div style="margin: 20px;">
            <form  method="POST" >{% csrf_token %}
                <div class="form-group form-control">
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-block btn-primary">Entrar</button>
            </form>
        <ul>
            <li> <br> <br> </li>
            <li>{% if tipo_usuario == 'conductor' %}
                <a href="{% url 'register_conductor' %}">¿Aún no tienes cuenta? Registrate!</a>
                {% else %}
                <a href="{% url 'register' %}">¿Aún no tienes cuenta? Registrate!</a>
                {% endif %}
            </li>
        </ul>
        </div>


    </div>

    
</div>
</div>
</section>

{% endblock %}

templates/mapa2.html
{% load static%}
<html>
    <head>
        <title>Te Lo Cuido</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js">
        <script src='https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.js'></script>
        <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.css">
        <link rel="stylesheet" href="{% static 'css/mapa.css' %}">
    </head>
    <body>

      <div class="jumbotron text-center" style="margin-bottom:0">
        <h1>Te Lo Cuido</h1>
        <p>Servicio de Cuidacoches </p>


      <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
          </ul>
        </div>

      </nav>
      <div id='map'></div>
<script>

{% for cuidacoches in coordenadas %}
    var lat{{ cuidacoches.ci }} = "{{ cuidacoches.latitud }}".toString().replace(",",".");
    var lon{{ cuidacoches.ci }} = "{{ cuidacoches.longitud }}".toString().replace(",",".");
{% endfor %}

  mapboxgl.accessToken = 'pk.eyJ1IjoicHJlb3llY3Rvd29vdyIsImEiOiJjazdvOTN5cGkwMWN1M2xtdmJ1MGRvd2s3In0.UrORy2QZRA_Gu5g8TGszAA';
  const map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://style/mapbox/streets-v11',
	  center: [-56.18697666757, -34.90508515797],
      zoom: 16
  });
  map.addControl(new mapboxgl.NavigationControl());
  map.addControl(new mapboxgl.FullscreenControl());
  map.addControl(new mapboxgl.GeolocateControl({
    positionOptions: {
        enableHighAccuracy: true
    },
    trackUserLocation: true
}));


{% for cuidacoches in coordenadas %}
  const m{{ cuidacoches.ci }} = new mapboxgl.Marker()
      .setLngLat([lon{{ cuidacoches.ci }}, lat{{ cuidacoches.ci }}])
      .setPopup(
            new mapboxgl.Popup({ offset: 25 }) // add popups
              .setHTML(
                '<h3><p>{{cuidacoches.nombre_trabajo}} </p></h3>'+
                  '<p>{{cuidacoches.nombre}} {{cuidacoches.apellido}}</p>' +
                      'Horario: ' +
                  ' de {{cuidacoches.horario_inicio}}' +
                  ' a {{ cuidacoches.horario_fin }}</p>' +
                  '<p> Cantidad de lugares libres: {{cuidacoches.lugares_disponibles}} </p>' +
                  '<p>{{cuidacoches.direccion}} </p>' +
                   '<a>¿Desea elegir este lugar?</a>'+
        '<form name = "nombre" method = "post">'+
            '{% csrf_token %}'+
            '<input type = "text" id="id_nombre" name="nombre" Value={{ cuidacoches.nombre }} style="display:none !important"/>'+
            '<input type = "text" id="id_apellido" name="apellido" Value={{ cuidacoches.apellido }} style="display:none">'+
            '<input type = "text" id="id_nombre_lugar_trabajo" name="nombre_lugar_trabajo" Value={{ cuidacoches.nombre_trabajo }} style="display:none"/>'+
            '<input type = "text" id="id_horario_inicio" name="horario_inicio" Value={{ cuidacoches.horario_inicio }} style="display:none"/>'+
            '<input type = "text" id="id_horario_fin" name="horario_fin" Value={{ cuidacoches.horario_fin }} style="display:none"/>'+
            '<input type = "text" id="id_num_registro" name="num_registro" Value={{ cuidacoches.num_registro }} style="display:none"/>'+
            '<input type = "submit" value="SI" />'
              )
          )
      .addTo(map);
{% endfor %}


    </script>
    </body>
</html>

templates/perfil_conductor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}TLC Inicio{% endblock %}

{% block content %}
<section class="view intro-1 hm-black-strong">
    <div class="container">
        <div style="background-color: rgba(255, 255, 255, 0.9); color: rgb(0, 19, 104); margin-top: 100px; overflow: scroll !important; height: 550px;" >
            <div style="margin: 20px;">
                <ul style="list-style:none !important"><li><br></li></ul>
                <ul style="list-style:none !important"><li><br></li></ul>
                
                   
                        <div class="card" style="background-color: #ffffff; text-align: center;">
                            <ul style="list-style:none !important"><li><br></li></ul>
                            <h3>Monto monedero:</h3> 
                            <h1><strong>$ {{monedero.monto}} </strong></h1><br>
                            <ul style="list-style:none !important"><li><br></li></ul>
                            <button class="btn btn-primary">Recargar desde la cuenta bancaria.</button>
                            <ul style="list-style:none !important"><li><br></li></ul>
                        </div>
                    
                        <ul style="list-style:none !important"><li><br></li></ul>
                        <ul style="list-style:none !important"><li><br></li></ul>
                    
    <div>
        <h3 style="text-align: center;">Servicios utilizados.</h3>
        {% if relaciones %}
            {% for relacion in relaciones %}
                <p class="card" style="text-align: center;">
                    
                    Fecha: {{relacion.fecha}} <br>
                    Cuidacoches: {{relacion.cuidacoches.nombre}} {{relacion.cuidacoches.apellido}} <br>
                    Lugar: {{relacion.cuidacoches.nombre_trabajo}} <br>
                    Tu calificación: 
                    {% if relacion.calificacion == 5%}   ★★★★★  
                    {% elif relacion.calificacion == 4%} ★★★★ 
                    {% elif relacion.calificacion == 3%} ★★★ 
                    {% elif relacion.calificacion == 2%} ★★ 
                    {% elif relacion.calificacion == 1%} ★ 
                    {% else %} sin calificacion
                    {% endif %}
                    
                    <br>
                    Tu propina: {% if relacion.propina  %} ${{relacion.propina}} {% else %} $0 {% endif %} <br>
                     
                </p>
                
            {% endfor %}
        {% else %}
            <p>
                Aún no has usado nuestro servicio de cuidacoches.
            </p>
        {% endif %}
    </div>
</div>
</div>
</div>
</section>


{% endblock %}

templates/perfil_cuidacoches.html
{% extends 'base.html' %}
{% load static %}
{% block title %}TLC Inicio{% endblock %}

{% block content %}
<section class="view intro-1 hm-black-strong">
    <div class="full-bg-img flex-center">
        <div class="container">

    

    <div style="background-color: rgba(255, 255, 255, 0.8); color: rgb(0, 19, 104);">

<body>
    <header><h2><strong>{{cuidacoches.nombre}} {{cuidacoches.apellido}}</strong>, cuidacoches</h2></header>
    <br>
    <br>
        <h1>ACÁ VA LA FOTO</h1>
        <h3>Promedio: {{cuidacoches.promedio_calificacion}}/5,0 (esto va con estrellitas)</h3>
        <p>Votos: {{cuidacoches.cantidad_votos}}</p>
    <br>
    <div>
        <h3>Comentarios.</h3>
        {% if relaciones %}
            {% for relacion in relaciones %}
                <p>
                    ---------------------------------------------------------- <br>
                            {{relacion.comentario}} <br>
                    ----------------------------------------------------------  <br>
                </p>
                
            {% endfor %}
        {% else %}
            <p>
                No hay comentarios aún.
            </p>
        {% endif %}
    </div>
</body>
    </div>
    
</div>
</div>
</section>

{% endblock %}

templates/portada.html
{% extends 'base.html' %}
{% load static %}
{% block title %}TLC Inicio{% endblock %}

{% block content %}
<section class="view intro-1 hm-black-strong">
    <div class="full-bg-img flex-center">
        <div class="container">

<ul>
    <div style="background-color: rgba(255, 255, 255, 0.8);">
        <li>

        <img class="h1-responsive font-bold wow fadeInDown sombra" data-wow-delay="0.2s" src="{% static 'img/IDEA_TLC.png' %}" alt="" height="200px" width="190px" 
        style="display:block;
        margin:auto; padding: 10px;">
        </li>
        <li>
        <p class="lead mt-4 mb-5 wow fadeInDown" style="color: rgb(0, 78, 122) ;">Tu servico de cuidacoches</p>
        </li>
    
        <li>
            <a target="_blank" href="{% url 'login_cuidacoches' %}" class="btn btn-primary btn-block wow fadeInLeft"  data-wow-delay="0.2s" rel="nofollow">Cuidacoches</a> <br>
            <a target="_blank" href="{% url 'login_conductor' %}" class="btn btn-default btn-block wow fadeInRight" data-wow-delay="0.2s" rel="nofollow">  Usuarios </a>
          
        </li>  
    </div>
</ul>

</div>
</div>
</section>
{% endblock %}

templates/pruebareg_cond.html
{% extends 'base.html' %}
{% load static %}
{% block title %}TLC Inicio{% endblock %}

{% block content %}
<section class="view intro-1 hm-black-strong">
    <div class="container">
        <div style="background-color: rgba(255, 255, 255, 0.9); color: rgb(0, 19, 104); margin-top: 100px; overflow: scroll !important; height: 550px;" >
            <div style="margin: 20px;">
                <ul style="list-style:none !important">
                <li>
                    <h2>{{mensaje}}</h2> 
                </li>
                <li><br></li>
                <li>

                
                <form method="POST" >
                    {% csrf_token %}
                    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Guardar</button>
</form>
</li>
<li><br></li><li><br></li><li><br></li>
</ul>
            </div>
            </div>
    </div>
</section>
    
{% endblock %}

templates/pruebareg_cuid.html
{% extends 'base.html' %}
{% load static %}
{% block title %}TLC Inicio{% endblock %}

{% block content %}
<section class="view intro-1 hm-black-strong">
    <div class="full-bg-img flex-center">
        <div class="container">
            <div style="background-color: rgba(255, 255, 255, 0.8); color: rgb(0, 19, 104);">

                {% if reg_imm %}
                <h3>Bienvenido {{reg_imm.nombre}} {{reg_imm.apellido}} <br> 
                    Complete sus datos para finalizar el registro.
                </h3>
                
                {% endif %}

                {{mensaje}}
                <form method="POST" >{% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Verificar</button>
                </form>

            </div>
        </div>
    </div>
</section>
    
{% endblock %}

templates/quienes_somos.html
{% extends 'base.html' %}
{% load static %}
{% block title %}TLC Inicio{% endblock %}

{% block content %}
<section class="view intro-1 hm-black-strong">
    <div class="full-bg-img flex-center">
        <div class="container">

    

    <div style="background-color: rgba(255, 255, 255, 0.8); color: rgb(0, 19, 104);">
        <div style="margin: 20px;">

            <img src=" {% static 'img/quienes_somos.png' %} " alt="no carga" width="100%">
        </div>


    </div>

    
</div>
</div>
</section>

{% endblock %}